---
# Install the package
- name: Install the RSVPD package
  package:
    name: perl-rsvpd
    state: latest
  become: yes

- name: Install the rsvpclient package
  package:
    name: perl-rsvpclient
    state: latest
  become: yes

- name: Start the RSVPD Service
  systemd:
    name: rsvpd
    state: started
  become: yes

- block:
  - name: Wait for RSVPD service to be active
    wait_for:
      port: "{{ port_number }}"

  # Open the RSVPD tcp port so machines can reach the service.
  - include_tasks: "{{ playbook_dir }}/library/firewall_port.yml"
    vars:
      port: "{{ port_number ~ '/tcp' }}"
      open: true
  vars:
    port_number: 1752 # The rsvp server we deploy listens on 1752.

# Add the RSVP classes
# For RHEL families we register only the major version of the distribution.
- name: Add the RSVP classes
  command: "/usr/bin/rsvpclient --dhost localhost add_class {{ item }}"
  register: result
  changed_when: "result.rc == 0"
  failed_when: "(result.rc != 0) and ('already exists' not in result.stderr)"
  with_items:
    - ALBIREO
    - ALL
    - FARM
    - VFARM
    - LINUX-UDS
    - LINUX-VDO
    - VDO
    - VDO-PMI
    - FEDORA
    - AARCH64
    - PPC64LE
    - S390X
    - X86_64
    - "{{ query('available_distributions')
          | map('regex_replace', '^((CENTOS|RHEL)\\d).*', '\\1')
          | unique
          | list }}"

- name: Add the RSVP resource classes
  command: "/usr/bin/rsvpclient  --dhost localhost add_resource_class {{ item }}"
  register: result
  changed_when: "result.rc == 0"
  failed_when: "(result.rc != 0) and ('already exists' not in result.stderr)"
  with_items:
    - MAINTENANCE
