---
- block:
  - name: SCAM data - Ansible
    copy:
      content: ANSIBLE=yes
      dest: /etc/scam/ansible.conf
      mode: 0644
    become: yes

  - name: SCAM data - DevVM
    lineinfile:
      line: DEVVM=yes
      path: /etc/scam/devvm.conf
      create: yes
      mode: 0644
      owner: root
      group: root
      state: "{%- if (is_devvm | bool) -%}
                present
              {%- else -%}
                absent
              {%- endif -%}"
    become: yes

  - name: SCAM data - Vagrant
    lineinfile:
      line: VAGRANT=yes
      path: /etc/scam/vagrant.conf
      create: yes
      mode: 0644
      owner: root
      group: root
      state: "{%- if (is_vagrant | bool) -%}
                present
              {%- else -%}
                absent
              {%- endif -%}"
    become: yes

  - name: SCAM data - farm
    copy:
      # If we put FARM outside the evaluation either the quoted no/yes results
      # in the quotes in the file or unquoted no/yes is treated as undefined
      # variables.
      content: "FARM={{ is_farm | ternary('yes', 'no') }}"
      dest: /etc/scam/farm.conf
      mode: 0644
    become: yes

  - name: SCAM data - Albireo
    copy:
      content: "ALBIREO={{ is_farm | ternary('yes', 'no') }}"
      dest: /etc/scam/albireo.conf
      mode: 0644
    become: yes

  - name: SCAM data - extra user vars
    lineinfile:
      line: "{{ item.var | upper }}={{ item.value }}"
      path: /etc/scam/{{ item.var | lower }}.conf
      create: yes
      mode: 0644
      owner: root
      group: root
      state: present
    become: yes
    with_items: "{{ extra_user_scam_vars }}"

